[project]
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mamushi>=0.0.4",
    "moccasin>=0.3.8",
    "snekmate>=0.1.0",
]

[tool.moccasin.project]
src = "src"
dependencies = ["snekmate"]
